### ISSUE TITLE
libusb.lwr: Fedora rpms use a package name of "libusbx"

### ISSUE THREAD

**Issue by awalls-cx18** [gnuradio/gr-recipes#10]
For libusb.lwr:

Currently the recipe uses:

   rpm: (libusb-devel >= 1.0.9) || (libusb-devel >= 1.0.9)

But on Fedora 20-23 the packages are "libusbx-devel" for libusb 1.0.x.
On Fedora 20-23 libusb-devel (no -x) refers to libusb 0.1.x, which is not what this recipe is trying to find.

Recommend changing the line to read:

     rpm: (libusb-devel >= 1.0.9) || (libusbx-devel >= 1.0.9)

**Comment by mbr0wn** [comment]
Lol that's what it's supposed to read.... Thanks!
