### ISSUE TITLE
Ubuntu 18.04 pyBOMBS install failing

### ISSUE THREAD

**Issue by oe1rsa** [gnuradio/gr-recipes#125]
Installation with pybombs from pypi fails with AssertionError.
Installation with pybombs from github fails with "AttributeError: 'Recipe' object has no attribute 'target'"
the only attributes that the r has at that time is r.optional == True

OS is Ubuntu 18.04

Any hints appreciated.

**Comment by mbr0wn** [comment]
This was fixed on the git version; I'll tag a release soon.
