### ISSUE TITLE
GNURadio needs GMP

### ISSUE THREAD

**Issue by cyrus104** [gnuradio/gr-recipes#126]
GNU Radio is not compiling and is looking for gmp or mpir. I added gmp to the requirements of gnuradio.lwr and this fixed my issue.

https://github.com/gnuradio/gr-recipes/blob/master/gnuradio.lwr#L20-L40

**Comment by mbr0wn** [comment]
3823dcab69eae22a427e2b04aae17630d5eade29

@cyrus104 Instead of submitting an issue, you can also submit a pull request with the changes.
