### ISSUE TITLE
gr-limesdr fails to compile on FC29, libusb 1.0.9 too old

### ISSUE THREAD

**Issue by svancau** [gnuradio/gr-recipes#139]
gr-limesdr fails to compile as it looks for a function not present in the libusb v1.0.9.
Going to libusb 1.0.22 fixed the issue. I'm not sure if everything can be moved to libusb 1.0.22 though.

**Comment by mbr0wn** [comment]
We can go to 1.0.20 if that fixes the issue. FC29 ships with 1.0.22, so I'm not sure how that issue you're describing even manifests?

**Comment by mbr0wn** [comment]
bff834e03ffc0b3d1ef494a741aabb1fb70c2efc might fix this. Please reopen if not.
