### ISSUE TITLE
PlutoSDR support, gr-osmosdr

### ISSUE THREAD

**Issue by JulioSDDR** [gnuradio/gr-recipes#143]
I am unable to make plutoSDR work with gqrx installing using pybombs. PlutoSDR does not apear in the device list. I am ussing debian, and following the next procedure:

`pip install git+https://github.com/gnuradio/pybombs.git`
`mkdir -p ~/radio`
`cd ~/radio`
`git clone https://github.com/gnuradio/pybombs`
`cd pybombs`
`python setup.py build`
`pybombs auto-config`
`pybombs recipes add-defaults`
`pybombs prefix init ~/radio -a radio -R gnuradio-default`
`pybombs install gr-iio`
`pybombs install gr-osmosdr `
`pybombs install gqrx`
`pybombs run gqrx
`

I have tried to change the source of the gr-osmosdr package to https://github.com/csete/gr-osmosdr-gqrx. Also, i have tried to comment out the line deb: gqrx-sdr at the gqrx recipe.
No changes. What may be the problem?

**Comment by ckuethe** [comment]
I recently added support for PlutoSDR to the SoapySDR recipes. If you `pybombs install soapyplutosdr` you should be able to tell gqrx to use a device string of the form `soapy,driver=...`

I don't have a plutosdr of my own, but it works soapysdr works with uhd, hackrf, lime, airspy, and rtlsdr.
