### ISSUE TITLE
Recipes tied to master

### ISSUE THREAD

**Issue by SpontaneousDuck** [gnuradio/gr-recipes#157]
Is there a reason why the recipes for gnuradio38 and uhd are set to gitbranch master? Both of those repositories mentioned carry out active development on master then create a branch for each new release version. This causes PyBOMBS to build whatever is being developed at the moment instead of known working and released code.

**Comment by SpontaneousDuck** [comment]
gnueradio38.lwr issue being fixed in #155. Added PR for UHD recipe

**Comment by mbr0wn** [comment]
It's also more of a default. Through recipe prefixes and config variables, there are ways to update the branch.
