### ISSUE TITLE
Missing UHD dependencies on Ubuntu 16.04

### ISSUE THREAD

**Issue by ptrkrysik** [gnuradio/gr-recipes#174]
I know 16.04's life is near to the end but in case anyone wants to install UHD on it with use of pybombs:
Currently pybombs installation won't work out of the box as it doesn't install python3 variation of 
mako, numpy, setuptools.

They can be installed with use of:
sudo apt install python3-mako python3-numpy pythonn3-setuptools

**Comment by velichkov** [comment]
Hi @ptrkrysik,

> Currently pybombs installation won't work out of the box as it doesn't install python3 variation of
mako, numpy, setuptools.

[Reinstall pybombs using `pip3`](https://github.com/gnuradio/pybombs/#using-python3) from the github URL or add [`python_ver: 3`](https://github.com/gnuradio/pybombs/#python-version) to your prefix configuration file.
```
sudo pip uninstall pybombs
sudo pip3 install --upgrade git+https://github.com/gnuradio/pybombs.git
```
