### ISSUE TITLE
gnuradio-master pybind11 dependency

### ISSUE THREAD

**Issue by mahdiaminik** [gnuradio/gr-recipes#241]
error pybombs install gnuradio-master :

CMake Error at CMakeLists.txt:339 (message):
  pybind11 version 2.0.1 < 2.4

Hi

building master branch of gnuradio needs pybind11 > 2.4 and its not stable release.
and it should be to "force build"

thanks

**Comment by argilo** [comment]
Fixed in #277.

**Comment by argilo** [comment]
Fixed in #277.
