### ISSUE TITLE
gr-iqbal needs branch support added

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gr-recipes#246]
As found in: https://github.com/gnuradio/gnuradio/issues/4154

The gr-iqbal OOT uses branches for the different GR versions (yey!) but the PyBOMBS recipe doesn't select the correct branch based on the GNU Radio version used.

**Comment by Timvrakas** [comment]
This just tripped me up. I fixed it with several `checkout origin/gr3.8`s in the right place, but it's a roadblock to a fresh install.

**Comment by Abraxas3d** [comment]
It still seems to be a problem. 

Attempted to install 3.9 with Pybombs to get around the Ubuntu package install producing the following failure (documented elsewhere by several others). 

```
Generating: '/home/abraxas3d/Documents/GNU-Radio-Flowgraphs/spyon915.py'
Generate Error: 'catch_exceptions'
>>> Failure

```
But, iqbal won't install. 

-mdt
