### ISSUE TITLE
gr-mac: upstream repo dead

### ISSUE THREAD

**Issue by scateu** [gnuradio/gr-recipes#285]
https://github.com/jmalsbury/gr-mac.git

upstream dead... sad.. 😭

**Comment by willcode** [comment]
That last update to gr-mac was in 2014. Did it still work? I had a clone of the repo, so I put it up at https://github.com/willcode/gr-mac, in case anyone needs it in the future.

**Comment by scateu** [comment]
ping @marcusmueller  

Maybe change that URL or delete that gr-mac recipe?

**Comment by willcode** [comment]
No, I'm not going to maintain it, but someone else is welcome to clone it, see if it works on v3.10, and we can go from there.

**Comment by scateu** [comment]
I see.

A little background story: We maintain a mirror for pybombs. Now the only failed 
url is from this recipe.

    https://mirrors.tuna.tsinghua.edu.cn/pybombs/failed.log

I can do a substitution in the mirror site. But I still think it's better to be 
fixed in here.

-- 
Wang Kang
Blog: http://scateu.me
Fingerprint: 011F 0492 97D6 5D75 8AC4  6458 D43F 3CE2 3353 B7BD
HAM Callsign: BH1RLW

**Comment by willcode** [comment]
We could just delete that recipe, if the OOT does not even have a reliable location.

**Comment by scateu** [comment]
Sure! Good idea. 

-- 
Wang Kang

**Comment by willcode** [comment]
OK, see if that works.

**Comment by scateu** [comment]
Great!  Thank you for maintaining gr-recipes.
