### ISSUE TITLE
UHD clone depth=1

### ISSUE THREAD

**Issue by mlw214** [gnuradio/gr-recipes#38]
By default the UHD recipe has gitargs of --depth=1, causing UHD to be shallow cloned. This has bitten me a number of times when I've altered the recipe to checkout a specific version of UHD but forgot to remove the gitargs statement. Is there any reason why the recipe shallow clones by default? No other recipe in this repo seems to do this.

**Comment by mbr0wn** [comment]
Yeah let's drop that.
