### ISSUE TITLE
x11 deb package names are case sensitive on Ubuntu 16

### ISSUE THREAD

**Issue by gr-sp** [gnuradio/gr-recipes#40]
I had an issue where my gnuradio build failed the x11 package on my Ubuntu 16 machine. I went poking around the pybombs code to see why and found that the `apt-cache search` was failing when it was attempting to get the x11 version available in the apt repo. I attempted to run the same command (that pybombs uses) manually on the command line (`apt-cache search libX11-dev`) and was surprised to see that the package could not be located. After a little more sleuthing I determined that the `libX11-dev` package name doesn't have the correct case. During my sleuthing I discovered that Ubuntu 14 doesn't behave the same way. The `apt-cache search libX11-dev` command succeeds even though the package is named `libx11-dev`.

The current names in x11.lwr are:
- libX11-dev
- libXrender-dev

They should be:
- libx11-dev
- libxrender-dev

I am surprised that no one has encountered this before.

**Comment by mbr0wn** [comment]
Fixed. aa4c27b3cfc86ae3fb28bf13abc7678bfed2b3b4
