### ISSUE TITLE
[gr-inspector] Requires libqwtplot3d-qt4-dev on Ubuntu 16.04

### ISSUE THREAD

**Issue by u0m3** [gnuradio/gr-recipes#56]
On Ubuntu 16.04 **QwtPlot3D** is packaged as **libqwtplot3d-qt4-dev** and as such is required.

**Comment by mbr0wn** [comment]
@sbmueller Can you take a look at this and please update the recipe?

**Comment by sbmueller** [comment]
Oh, this is a new dependency resulting from @chrisruk s AMC update. I will take a look.

**Comment by chrisruk** [comment]
@sbmueller I've just looked at the package names you added in https://github.com/sbmueller/gr-recipes/blob/gr-inspector/qwtplot3d.lwr they look correct to me.

**Comment by mbr0wn** [comment]
@sbmueller fixed it.
