### ISSUE TITLE
Airprobe recipe only downloads source files

### ISSUE THREAD

**Issue by ptrkrysik** [gnuradio/gr-recipes#6]
I have little issue with the process of selection of recipes to the main GNU Radio recipe repository. There is for example airprobe recipe. It only downloads airprobe files, which are now only historical relict as none of the GNU Radio related projects inside can be build with current GNU Radio versions. In my opinion this recipe should be moved to the gr-etcetera repository or removed totally as it will be only source of frustration to the GNU Radio users.

There is gr-gsm project that does what airprobe did but better and in a cleaner manner. Only missing functionality is compatibility of the output with Kraken (GSM's encryption cracker) that I have doubt to implement due to ethical reasons (this can be easily implemented by the user however).

**Comment by mbr0wn** [comment]
Good point about demoting airprobe. Done.
