### ISSUE TITLE
No libfaad-devel package on Fedora

### ISSUE THREAD

**Issue by mpbraendli** [gnuradio/gr-recipes#61]
Hi there,

faad.lwr specifies

```
rpm: libfaad-devel
```

but that package name seems to be incorrect. The fedora 23 install next to me includes a faad2-devel package in the rpmfusion repository instead.
Best regards,
mpb

**Comment by mbr0wn** [comment]
331954ac4bc8c6ffc00faa3da14030a9d7978291 and 331954ac4bc8c6ffc00faa3da14030a9d7978291
