### ISSUE TITLE
gr-drm.lwr depends on faac, but there's no faac.lwr

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gr-recipes#74]

**Comment by mbr0wn** [comment]
Is it maybe faad?

**Comment by marcusmueller** [comment]
gr-drm depends on both faac and faad. faad's just the decoder!

**Comment by ckuethe** [comment]
https://github.com/gnuradio/gr-etcetera/blob/master/faac.lwr

**Comment by mbr0wn** [comment]
Yup guess so. Moved over.
