### ISSUE TITLE
libudev.lwr not working on Centos 7 

### ISSUE THREAD

**Issue by ajd394** [gnuradio/gr-recipes#82]
the recipe specified `rpm: libgudev-devel` but i think it should be `rpm: libudev-devel`. Without this fix, the install fails because libgudev-devel does not exists in the centos 7 repo. Not sure if we still need libgudev-devel but i think we should probably at least do `rpm: libgudev-devel || libudev-devel`

**Comment by ajd394** [comment]
@mbr0wn Seems like you made the last mod to this recipe. Thoughts?

**Comment by mbr0wn** [comment]
:+1: Pushed a fix.
