### ISSUE TITLE
Apache Thrift 0.9.3 fails to build on Fedora 26

### ISSUE THREAD

**Issue by awalls-cx18** [gnuradio/gr-recipes#88]
Apache Thrift 0.9.3 fails to build on Fedora 26, because libcrypto from the latest openssl shipping with Fedora 26 has changed enough for it to matter to thrift 0.9.3's configure script.

Apparently thrift 0.10.0 has addressed this issue, and Fedora 26 provides thrift-0.10.0 and thrift-devel-0.10.0 as distro packages.  https://bugzilla.redhat.com/show_bug.cgi?id=1385702

The GNURadio wiki claims that 0.9.3 or higher is acceptable:
https://wiki.gnuradio.org/index.php/ControlPort

**Comment by argilo** [comment]
The same problem occurs on Ubuntu 18.04. I tried updating the apache-thrift recipe to use Thrift 0.11.0, but then gnuradio fails to build.

To work around the problem, I simply removed apache-thrift from the dependency list in the gnuradio recipe.

**Comment by mbr0wn** [comment]
Upgraded to 0.10.0.
