### ISSUE TITLE
pybombs PYTHONPATH, SoapySDR, and python3

### ISSUE THREAD

**Issue by guruofquality** [gnuradio/gr-recipes#91]
Not sure who to contact here, but I found [SoapySDR.lwr](https://github.com/gnuradio/gr-recipes/blob/master/soapysdr.lwr) in this repo, so I'm leaving a message:

* Here is the issue https://github.com/pothosware/SoapySDR/issues/132

In short, SoapySDR tries to build for python3, and although that may not be useful for gnuradio, the current pybombs build may have some PYTHONPATH settings that cause the cmake configure to bomb out when python3 is installed. Happened to a few users so far.

My suspicion is that pybombs sets PYTHONPATH for python2-ish reasons, but this causes a failure when SoapySDR cmake tries to talk to python3 to discover the install path.

* I would like to confirm that PYTHONPATH is overwritten in a way that would make python3 import statements fail (more inside the issue mentioned above)
* And two, in the near term, add a cmake argument to the lwr file with `-DENABLE_PYTHON3=OFF` to avoid this problem

Any comments ideas?

**Comment by Mavrikant** [comment]
What you guy waiting for fixing this. I got the same error while installing with PyBOMBS. I changed my local recipe like @velichkov [did](https://github.com/velichkov/gr-recipes/commit/fade356837b822264d72697e851b860fb92fa827) and it works.
